backend:
  name: git-gateway
  branch: master
  commit_messages:
    create: 'Create {{collection}} “{{slug}}”'
    update: 'Update {{collection}} “{{slug}}”'
    delete: 'Delete {{collection}} “{{slug}}”'
    uploadMedia: '[skip ci] Upload “{{path}}”'
    deleteMedia: '[skip ci] Delete “{{path}}”'

media_folder: static/uploads
public_folder: /uploads

collections:
  - name: pages
    label: Pages
    files:
      - file: src/pages/index.md
        name: index-page
        label: Home Page
        fields:
          - name: greet
            label: Greet
            widget: string
